import JsBarcode from 'jsbarcode';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface UserQRData {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  role: string;
  username: string;
}

/**
 * Generate barcode data URL for a user
 */
export const generateUserBarcode = async (userData: UserQRData): Promise<string> => {
  // Create a unique barcode value using user ID
  const barcodeValue = `GMS${userData.id.toString().padStart(6, '0')}`;

  try {
    // Create a canvas element
    const canvas = document.createElement('canvas');

    // Generate barcode on canvas
    JsBarcode(canvas, barcodeValue, {
      format: 'CODE128',
      width: 2,
      height: 60,
      displayValue: true,
      fontSize: 14,
      margin: 10,
      background: '#FFFFFF',
      lineColor: '#000000',
    });

    // Convert canvas to data URL
    const barcodeDataURL = canvas.toDataURL('image/png');
    return barcodeDataURL;
  } catch (error) {
    console.error('Error generating barcode:', error);
    throw new Error('Failed to generate barcode');
  }
};

/**
 * Generate PDF with user details and barcode
 */
export const generateUserPDF = async (
  userData: UserQRData,
  barcodeDataURL: string
): Promise<void> => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  // Colors
  const primaryColor = [59, 130, 246]; // Blue
  const secondaryColor = [107, 114, 128]; // Gray
  const accentColor = [16, 185, 129]; // Green

  // Header with gradient background
  pdf.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  pdf.rect(0, 0, pageWidth, 40, 'F');

  // Title
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('GYM MANAGEMENT SYSTEM', pageWidth / 2, 25, { align: 'center' });

  // Subtitle
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text('User Registration Card', pageWidth / 2, 35, { align: 'center' });

  // User Info Section
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('USER INFORMATION', 20, 60);

  // User details
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');

  const details = [
    { label: 'Full Name:', value: `${userData.first_name} ${userData.last_name}` },
    { label: 'Email:', value: userData.email },
    { label: 'Username:', value: userData.username },
    { label: 'Role:', value: getRoleDisplayName(userData.role) },
    { label: 'User ID:', value: userData.id.toString() },
    { label: 'Registration Date:', value: new Date().toLocaleDateString() },
  ];

  let yPosition = 75;
  details.forEach((detail) => {
    pdf.setFont('helvetica', 'bold');
    pdf.text(detail.label, 20, yPosition);
    pdf.setFont('helvetica', 'normal');
    pdf.text(detail.value, 80, yPosition);
    yPosition += 8;
  });

  // Barcode Section
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('BARCODE ACCESS', 20, yPosition + 15);

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Scan this barcode for quick access and verification', 20, yPosition + 25);

  // Add Barcode
  try {
    // Convert data URL to image and add to PDF
    const barcodeImage = new Image();
    barcodeImage.src = barcodeDataURL;

    // Wait for image to load
    await new Promise((resolve) => {
      barcodeImage.onload = resolve;
    });

    // Add barcode to PDF
    pdf.addImage(barcodeDataURL, 'PNG', pageWidth - 80, yPosition + 5, 60, 60);
  } catch (error) {
    console.error('Error adding barcode to PDF:', error);
    // Fallback: add text instruction
    pdf.setFontSize(10);
    pdf.text('Barcode generation failed', pageWidth - 80, yPosition + 35);
  }

  // Instructions
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  const instructions = [
    '• Keep this card safe and secure',
    '• Use barcode for gym access and check-in',
    '• Contact support if you lose this card',
    '• Valid for gym facilities and services',
  ];

  yPosition += 80;
  instructions.forEach((instruction) => {
    pdf.text(instruction, 20, yPosition);
    yPosition += 6;
  });

  // Footer
  pdf.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  pdf.rect(0, pageHeight - 20, pageWidth, 20, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Generated by Gym Management System', pageWidth / 2, pageHeight - 10, { align: 'center' });
  pdf.text(`Generated on ${new Date().toLocaleString()}`, pageWidth / 2, pageHeight - 5, { align: 'center' });

  // Save the PDF
  const fileName = `user-card-${userData.username}-${Date.now()}.pdf`;
  pdf.save(fileName);
};

/**
 * Get display name for user role
 */
const getRoleDisplayName = (role: string): string => {
  switch (role.toUpperCase()) {
    case 'USER':
      return 'Regular User';
    case 'ADMIN':
      return 'Administrator';
    case 'TRAINEE':
      return 'Trainer';
    default:
      return role;
  }
};

/**
 * Generate and download user PDF with barcode
 */
export const generateAndDownloadUserPDF = async (userData: UserQRData): Promise<void> => {
  try {
    const barcodeDataURL = await generateUserBarcode(userData);
    await generateUserPDF(userData, barcodeDataURL);
  } catch (error) {
    console.error('Error generating user PDF:', error);
    throw new Error('Failed to generate user PDF');
  }
};